# 私有 Harbor 仓库拉取凭据（docker-registry 类型）
apiVersion: v1
kind: Secret
metadata:
  name: links-registry-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.harbor.registry .Values.harbor.username .Values.harbor.password (printf "%s:%s" .Values.harbor.username .Values.harbor.password | b64enc) | b64enc | quote }}
