# 干净的闭环测试：alpine 从未在集群中出现过，必须真实从 Harbor 拉取
apiVersion: v1
kind: Pod
metadata:
  name: harbor-test2
spec:
  containers:
    - name: alpine
      image: harbor.k8s.local:30443/blog-project/alpine:v1
      command: ["sleep", "3600"]
  imagePullSecrets:
    - name: harbor-secret
