# Ansible 主机清单
# 单节点集群（kubeadm 部署于 192.168.80.133）
[all:vars]
ansible_user=zqq
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_become=true

[master]
k8s-master ansible_host=192.168.80.133

[nodes]
k8s-node01 ansible_host=192.168.80.11
# k8s-node02 ansible_host=192.168.80.12
